### ISSUE TITLE
Failed to load a language-property-list package grammar

### ISSUE THREAD

**Issue by SeanFloresDOMO** [atom/language-property-list#18] opened 2017-09-15 19:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [language-property-list](https://github.com/atom/language-property-list) package 0.9.1

### Stack Trace

Failed to load a language-property-list package grammar

```
At ENOENT: no such file or directory, open 'C:\ProgramData\Sean.Flores\atom\app-1.20.0\resources\app\node_modules\language-property-list\grammars\property list (xml).json' in C:\ProgramData\Sean.Flores\atom\app-1.20.0\resources\app\node_modules\language-property-list\grammars\property list (xml).json

Error: ENOENT: no such file or directory, open 'C:\ProgramData\Sean.Flores\atom\app-1.20.0\resources\app\node_modules\language-property-list\grammars\property list (xml).json'
  at C:/ProgramData/Sean.Flores/atom/app-1.20.0/resources/app/node_modules/language-property-list/grammars/property list (xml).json:1:1
```

### Commands

```
```

### Non-Core Packages

```
aligner-javascript 1.3.0 
atom-beautify 0.30.5 
atom-material-ui 2.0.4 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
busy-signal 1.4.3 
emmet 2.4.3 
fonts 3.0.3 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.74.2 
linter 2.2.0 
linter-csslint 2.0.0 
linter-htmlhint 1.3.3 
linter-jshint 3.1.5 
linter-ui-default 1.6.10 
minimap 4.29.6 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
open-recent 5.0.0 
pigments 0.40.2 
project-manager 3.3.5 
rest-client 1.3.1 
seti-ui 1.9.0 
sync-settings 0.8.3 
todo-show 2.0.0 
up2date 0.1.2 
```

**Comment by 50Wliu** [comment] 2017-09-15 21:17
Thanks for taking the time to contribute!

We noticed that this is a duplicate of atom/language-java#94. You may want to subscribe there for updates.

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close duplicates to focus our work and not have to touch the same chunk of code for the same reason multiple times. This is also why we may mark something as duplicate that isn't an exact duplicate but is closely related.

**Closed by 50Wliu** 2017-09-15 21:17 UTC
